name: Terraform Destroy
on: 
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        required: true
        type: string
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
