name: Terraform Destroy
on: 
  workflow_call:
    inputs:
    #secrets: 
      AWS_ACCESS_KEY_ID:
        required: true
        type: string
      AWS_SECRET_ACCESS_KEY:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      cli_config_credentials_token:
        required: true
        type: string


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ inputs.TF_API_TOKEN }}
      
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        
      # checks that all terraform configuration files syntax
      - name: Terraform Validate
        run: terraform validate

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan 

          
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
